// ==UserScript==
// @name                 🏷️ UTags - Add usertags to links
// @namespace            https://utags.pipecraft.net/
// @homepageURL          https://github.com/utags/utags#readme
// @supportURL           https://github.com/utags/utags/issues
// @version              0.23.2
// @icon                 data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='%23ff6361' class='bi bi-tags-fill' viewBox='0 0 16 16'%3E %3Cpath d='M2 2a1 1 0 0 1 1-1h4.586a1 1 0 0 1 .707.293l7 7a1 1 0 0 1 0 1.414l-4.586 4.586a1 1 0 0 1-1.414 0l-7-7A1 1 0 0 1 2 6.586V2zm3.5 4a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z'/%3E %3Cpath d='M1.293 7.793A1 1 0 0 1 1 7.086V2a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l.043-.043-7.457-7.457z'/%3E %3C/svg%3E
// @author               Pipecraft
// @license              MIT
// @match                https://*.utags.link/*
// @match                https://*.utags.top/*
// @match                https://*.utags.plus/*
// @match                https://*.utags.vip/*
// @match                https://x.com/*
// @match                https://twitter.com/*
// @match                https://github.com/*
// @match                https://www.reddit.com/*
// @match                https://www.instagram.com/*
// @match                https://www.threads.com/*
// @match                https://www.threads.net/*
// @match                https://*.facebook.com/*
// @match                https://*.youtube.com/*
// @match                https://www.tiktok.com/*
// @match                https://*.bilibili.com/*
// @match                https://*.biligame.com/*
// @match                https://greasyfork.org/*
// @match                https://lobste.rs/*
// @match                https://news.ycombinator.com/*
// @match                https://*.v2ex.com/*
// @match                https://*.v2ex.co/*
// @match                https://*.zhihu.com/*
// @match                https://*.weibo.com/*
// @match                https://*.weibo.cn/*
// @match                https://*.douban.com/*
// @match                https://www.52pojie.cn/*
// @match                https://juejin.cn/*
// @match                https://mp.weixin.qq.com/*
// @match                https://www.xiaohongshu.com/*
// @match                https://sspai.com/*
// @match                https://www.douyin.com/*
// @match                https://podcasts.google.com/*
// @match                https://sleazyfork.org/*
// @match                https://tilde.news/*
// @match                https://www.journalduhacker.net/*
// @match                https://rebang.today/*
// @match                https://myanimelist.net/*
// @match                https://www.pixiv.net/*
// @match                https://meta.discourse.org/*
// @match                https://linux.do/*
// @match                https://idcflare.com/*
// @match                https://meta.appinn.net/*
// @match                https://community.openai.com/*
// @match                https://community.cloudflare.com/*
// @match                https://community.wanikani.com/*
// @match                https://forum.cursor.com/*
// @match                https://forum.obsidian.md/*
// @match                https://forum-zh.obsidian.md/*
// @match                https://bbs.nga.cn/*
// @match                https://nga.178.com/*
// @match                https://ngabbs.com/*
// @match                https://www.dlsite.com/*
// @match                https://keylol.com/*
// @match                https://kemono.cr/*
// @match                https://kemono.su/*
// @match                https://coomer.st/*
// @match                https://coomer.su/*
// @match                https://nekohouse.su/*
// @match                https://rule34video.com/*
// @match                https://rule34gen.com/*
// @match                https://panda.chaika.moe/*
// @match                https://bbs.tampermonkey.net.cn/*
// @match                https://discuss.flarum.org/*
// @match                https://discuss.flarum.org.cn/*
// @match                https://yuanliao.info/*
// @match                https://www.nodeloc.com/*
// @match                https://veryfb.com/*
// @match                https://www.nodeseek.com/*
// @match                https://www.deepflood.com/*
// @match                https://*.inoreader.com/*
// @match                https://kater.me/*
// @match                https://bbs.viva-la-vita.org/*
// @match                https://www.zhipin.com/*
// @match                https://*.twitch.tv/*
// @match                https://*.yamibo.com/*
// @match                https://*.flickr.com/*
// @match                https://*.ruanyifeng.com/*
// @match                https://www.uscardforum.com/*
// @match                https://2libra.com/*
// @match                https://www.toutiao.com/*
// @match                https://v2hot.pipecraft.net/*
// @match                https://utags.pipecraft.net/*
// @match                https://*.pipecraft.net/*
// @include              https://*.utags.link/*
// @include              https://x.com/*
// @include              https://www.reddit.com/*
// @include              https://github.com/*
// @include              https://www.instagram.com/*
// @include              https://www.tiktok.com/*
// @include              https://*.youtube.com/*
// @include              https://greasyfork.org/*
// @include              https://*.dmm.co.j*/*
// @include              https://e*hentai.org/*
// @include              https://*.p*nhub.com/*
// @include              https://*.e*hentai.org/*
// @include              https://xsijishe.net/*
// @include              https://xsijishe.com/*
// @include              https://xsijishe.ink/*
// @include              https://sjs47.com/*
// @include              https://sjs47.net/*
// @include              https://sjslt.cc/*
// @include              https://simpcity.cr/*
// @include              https://simpcity.su/*
// @include              https://simpcity.is/*
// @include              https://simpcity.cz/*
// @include              https://simpcity.hk/*
// @include              https://simpcity.rs/*
// @include              https://simpcity.ax/*
// @connect              dav.jianguoyun.com
// @connect              localhost
// @connect              *
// @run-at               document-start
// @grant                GM.info
// @grant                GM.addValueChangeListener
// @grant                GM.getValue
// @grant                GM.deleteValue
// @grant                GM.setValue
// @grant                GM_addElement
// @grant                GM.registerMenuCommand
// @grant                GM.xmlHttpRequest
// @grant                GM_xmlhttpRequest
// @downloadURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/F09F8FB7EFB88F20UTags2020Add20usertags20to20links.user.js
// @updateURL https://raw.githubusercontent.com/FiorenMas/Userscripts/release/release/F09F8FB7EFB88F20UTags2020Add20usertags20to20links.meta.js
// ==/UserScript==
